### PR TITLE
refactor to inherit from collection

### PR DESCRIPTION
**Pull request by EvilDrW**
in my opinion, it is better for the fileupload resource to inherit from collection, not resource.  doing so gives us the advantage of maintaining a consistent interface with deployd (queries, script domains, etc. are identical to what deployd supplies).

in addition, it makes the code much shorter and most importantly gives us access to the dashboard to show all of the files.

as an aside, i sacrificed the option to not have unique filenames.  to me it was problematic because of the possibility of clobbering someone else's files.

### CODE REVIEW

**Comment by EvilDrW** [comment]
additionally, this addresses #10 and #8 (the latter because it enforces always using unique filenames)

**Comment by NicolasRitouet** [comment]
Looks good. :+1: 
Give me a few days to review this.
(and can you fix the conflicts?)

**Comment by EvilDrW** [comment]
ok!

**Comment by NicolasRitouet** [comment]
@EvilDrW 
Sorry for the delay, I'll try to review your PR in the coming days.

**Comment by israelroldan** [comment]
I have been testing this fork and it seems like a great step forward! PUT support is definitely missed, especially if you just want to update a non-file-related field, but there are ways to work around this of course. :+1:

**Comment by NicolasRitouet** [comment]
@israelroldan thanks for the feedback, I'll take care of this (I also have to publish a new release of deployd :/ )

**Comment by NicolasRitouet** [comment]
Thanks a lot @EvilDrW for your contribution!

**Comment by NicolasRitouet** [comment]
@EvilDrW 
this change has been released as an 1.0.0-alpha version and is available under the next tag:
`npm install dpd-fileupload@next --save`

Let me know if all works fine, and I'll make a final release

**Pull request merged**
