### PR TITLE
add single file get

### PR DESCRIPTION
**Pull request by EvilDrW**

### CODE REVIEW

**Comment by EvilDrW** [comment]
i added a test for the new feature, but one of the existing tests (for multiple file upload) always failed.  i adjusted the put/post method very slightly so that the old test passed.

**Comment by NicolasRitouet** [comment]
@EvilDrW 
To make your test pass, you need to clean the DB first.
I would recommend to upload a file specificaly for your test and run your test on this file.
Something like this:
https://gist.github.com/NicolasRitouet/3c4a777b9cc82a047447

**Comment by EvilDrW** [comment]
I don't understand what you're referring to.  When I run npm test in my VM,
it shows all tests pass...

**Comment by NicolasRitouet** [comment]
They don't pass on travis CI:
https://travis-ci.org/NicolasRitouet/dpd-fileupload/jobs/89373025

**Comment by EvilDrW** [comment]
I guess it was an order of operations thing.  Adjusted the test so that it passes.

**Comment by NicolasRitouet** [comment]
Thx, merged.
I'll release a new version soon.

**Comment by NicolasRitouet** [comment]
@EvilDrW I just released v0.0.16 with your PR

**Pull request merged**
