### PR TITLE
BeforeRequest and AfterCommit Event

### PR DESCRIPTION
**Pull request by rgolea**
I've finally managed to have time to rewrite everything and make it so you can merge it nicely. Test it and give me a feedback.

### CODE REVIEW

**Comment by israelroldan** [comment]
If #47 gets merged this will most likely come there as well as these two events will be delegated to the underlying collection (Coincidentally I just sent PR #1 against EvilDrW's fork)

**Comment by rgolea** [comment]
Sure! That'd be great... Just let me know when it's going to happen and what will the new api be for events... I'm using the module in production so I really want it to not go far away from the master branch of this project. Right now, I'm using my own.

**Comment by israelroldan** [comment]
ok, so it seems that my PR to EvilDrW's fork didn't make it in time so the availability of AfterCommit and BeforeRequest is not there yet (even now that #47 has just been merged). Given that you're the owner of this PR, could I suggest you a different implementation approach? Now that FIleUpload inherits from Collection it's just a matter of exposing the events in the ``Fileupload.events`` array on line 94 of index.js, the underlying collection can take care of the rest.

**Comment by rgolea** [comment]
I'm not really sure what to do next. My entire project is currently depending on this module as it was. In order to use that PR, I need all the events that the collections can bring me because I was using a this module with a normal collection based on the "fileupload" suffix. I might not make the changes in the end. @israelroldan, try to send yourself a PR since I really don't have time to implement it. I might be able to do some workaround later on...

**Comment by rgolea** [comment]
PS: Besides, the current folder name has changed.

**Pull request closed without merging**
